//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSECRContainerImageDetails) DeepCopyInto(out *AWSECRContainerImageDetails) {
	*out = *in
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSECRContainerImageDetails.
func (in *AWSECRContainerImageDetails) DeepCopy() *AWSECRContainerImageDetails {
	if in == nil {
		return nil
	}
	out := new(AWSECRContainerImageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchCheckLayerAvailabilityRequest) DeepCopyInto(out *BatchCheckLayerAvailabilityRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchCheckLayerAvailabilityRequest.
func (in *BatchCheckLayerAvailabilityRequest) DeepCopy() *BatchCheckLayerAvailabilityRequest {
	if in == nil {
		return nil
	}
	out := new(BatchCheckLayerAvailabilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchDeleteImageRequest) DeepCopyInto(out *BatchDeleteImageRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchDeleteImageRequest.
func (in *BatchDeleteImageRequest) DeepCopy() *BatchDeleteImageRequest {
	if in == nil {
		return nil
	}
	out := new(BatchDeleteImageRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchGetImageRequest) DeepCopyInto(out *BatchGetImageRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchGetImageRequest.
func (in *BatchGetImageRequest) DeepCopy() *BatchGetImageRequest {
	if in == nil {
		return nil
	}
	out := new(BatchGetImageRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompleteLayerUploadRequest) DeepCopyInto(out *CompleteLayerUploadRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompleteLayerUploadRequest.
func (in *CompleteLayerUploadRequest) DeepCopy() *CompleteLayerUploadRequest {
	if in == nil {
		return nil
	}
	out := new(CompleteLayerUploadRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompleteLayerUploadResponse) DeepCopyInto(out *CompleteLayerUploadResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompleteLayerUploadResponse.
func (in *CompleteLayerUploadResponse) DeepCopy() *CompleteLayerUploadResponse {
	if in == nil {
		return nil
	}
	out := new(CompleteLayerUploadResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreatePullThroughCacheRuleRequest) DeepCopyInto(out *CreatePullThroughCacheRuleRequest) {
	*out = *in
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistry != nil {
		in, out := &in.UpstreamRegistry, &out.UpstreamRegistry
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistryURL != nil {
		in, out := &in.UpstreamRegistryURL, &out.UpstreamRegistryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreatePullThroughCacheRuleRequest.
func (in *CreatePullThroughCacheRuleRequest) DeepCopy() *CreatePullThroughCacheRuleRequest {
	if in == nil {
		return nil
	}
	out := new(CreatePullThroughCacheRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreatePullThroughCacheRuleResponse) DeepCopyInto(out *CreatePullThroughCacheRuleResponse) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistry != nil {
		in, out := &in.UpstreamRegistry, &out.UpstreamRegistry
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistryURL != nil {
		in, out := &in.UpstreamRegistryURL, &out.UpstreamRegistryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreatePullThroughCacheRuleResponse.
func (in *CreatePullThroughCacheRuleResponse) DeepCopy() *CreatePullThroughCacheRuleResponse {
	if in == nil {
		return nil
	}
	out := new(CreatePullThroughCacheRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateRepositoryRequest) DeepCopyInto(out *CreateRepositoryRequest) {
	*out = *in
	if in.EncryptionConfiguration != nil {
		in, out := &in.EncryptionConfiguration, &out.EncryptionConfiguration
		*out = new(EncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateRepositoryRequest.
func (in *CreateRepositoryRequest) DeepCopy() *CreateRepositoryRequest {
	if in == nil {
		return nil
	}
	out := new(CreateRepositoryRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreateRepositoryResponse) DeepCopyInto(out *CreateRepositoryResponse) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(Repository_SDK)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateRepositoryResponse.
func (in *CreateRepositoryResponse) DeepCopy() *CreateRepositoryResponse {
	if in == nil {
		return nil
	}
	out := new(CreateRepositoryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteLifecyclePolicyRequest) DeepCopyInto(out *DeleteLifecyclePolicyRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteLifecyclePolicyRequest.
func (in *DeleteLifecyclePolicyRequest) DeepCopy() *DeleteLifecyclePolicyRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteLifecyclePolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteLifecyclePolicyResponse) DeepCopyInto(out *DeleteLifecyclePolicyResponse) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteLifecyclePolicyResponse.
func (in *DeleteLifecyclePolicyResponse) DeepCopy() *DeleteLifecyclePolicyResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteLifecyclePolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletePullThroughCacheRuleRequest) DeepCopyInto(out *DeletePullThroughCacheRuleRequest) {
	*out = *in
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletePullThroughCacheRuleRequest.
func (in *DeletePullThroughCacheRuleRequest) DeepCopy() *DeletePullThroughCacheRuleRequest {
	if in == nil {
		return nil
	}
	out := new(DeletePullThroughCacheRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletePullThroughCacheRuleResponse) DeepCopyInto(out *DeletePullThroughCacheRuleResponse) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistryURL != nil {
		in, out := &in.UpstreamRegistryURL, &out.UpstreamRegistryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletePullThroughCacheRuleResponse.
func (in *DeletePullThroughCacheRuleResponse) DeepCopy() *DeletePullThroughCacheRuleResponse {
	if in == nil {
		return nil
	}
	out := new(DeletePullThroughCacheRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteRegistryPolicyResponse) DeepCopyInto(out *DeleteRegistryPolicyResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRegistryPolicyResponse.
func (in *DeleteRegistryPolicyResponse) DeepCopy() *DeleteRegistryPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteRegistryPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteRepositoryPolicyRequest) DeepCopyInto(out *DeleteRepositoryPolicyRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRepositoryPolicyRequest.
func (in *DeleteRepositoryPolicyRequest) DeepCopy() *DeleteRepositoryPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteRepositoryPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteRepositoryPolicyResponse) DeepCopyInto(out *DeleteRepositoryPolicyResponse) {
	*out = *in
	if in.PolicyText != nil {
		in, out := &in.PolicyText, &out.PolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRepositoryPolicyResponse.
func (in *DeleteRepositoryPolicyResponse) DeepCopy() *DeleteRepositoryPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteRepositoryPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteRepositoryRequest) DeepCopyInto(out *DeleteRepositoryRequest) {
	*out = *in
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRepositoryRequest.
func (in *DeleteRepositoryRequest) DeepCopy() *DeleteRepositoryRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteRepositoryRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteRepositoryResponse) DeepCopyInto(out *DeleteRepositoryResponse) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(Repository_SDK)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRepositoryResponse.
func (in *DeleteRepositoryResponse) DeepCopy() *DeleteRepositoryResponse {
	if in == nil {
		return nil
	}
	out := new(DeleteRepositoryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImageReplicationStatusRequest) DeepCopyInto(out *DescribeImageReplicationStatusRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImageReplicationStatusRequest.
func (in *DescribeImageReplicationStatusRequest) DeepCopy() *DescribeImageReplicationStatusRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeImageReplicationStatusRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImageReplicationStatusResponse) DeepCopyInto(out *DescribeImageReplicationStatusResponse) {
	*out = *in
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImageReplicationStatusResponse.
func (in *DescribeImageReplicationStatusResponse) DeepCopy() *DescribeImageReplicationStatusResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeImageReplicationStatusResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImageScanFindingsRequest) DeepCopyInto(out *DescribeImageScanFindingsRequest) {
	*out = *in
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImageScanFindingsRequest.
func (in *DescribeImageScanFindingsRequest) DeepCopy() *DescribeImageScanFindingsRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeImageScanFindingsRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImageScanFindingsResponse) DeepCopyInto(out *DescribeImageScanFindingsResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImageScanFindingsResponse.
func (in *DescribeImageScanFindingsResponse) DeepCopy() *DescribeImageScanFindingsResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeImageScanFindingsResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImagesRequest) DeepCopyInto(out *DescribeImagesRequest) {
	*out = *in
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImagesRequest.
func (in *DescribeImagesRequest) DeepCopy() *DescribeImagesRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeImagesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeImagesResponse) DeepCopyInto(out *DescribeImagesResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeImagesResponse.
func (in *DescribeImagesResponse) DeepCopy() *DescribeImagesResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeImagesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribePullThroughCacheRulesRequest) DeepCopyInto(out *DescribePullThroughCacheRulesRequest) {
	*out = *in
	if in.ECRRepositoryPrefixes != nil {
		in, out := &in.ECRRepositoryPrefixes, &out.ECRRepositoryPrefixes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribePullThroughCacheRulesRequest.
func (in *DescribePullThroughCacheRulesRequest) DeepCopy() *DescribePullThroughCacheRulesRequest {
	if in == nil {
		return nil
	}
	out := new(DescribePullThroughCacheRulesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribePullThroughCacheRulesResponse) DeepCopyInto(out *DescribePullThroughCacheRulesResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.PullThroughCacheRules != nil {
		in, out := &in.PullThroughCacheRules, &out.PullThroughCacheRules
		*out = make([]*PullThroughCacheRule_SDK, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PullThroughCacheRule_SDK)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribePullThroughCacheRulesResponse.
func (in *DescribePullThroughCacheRulesResponse) DeepCopy() *DescribePullThroughCacheRulesResponse {
	if in == nil {
		return nil
	}
	out := new(DescribePullThroughCacheRulesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeRegistryResponse) DeepCopyInto(out *DescribeRegistryResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeRegistryResponse.
func (in *DescribeRegistryResponse) DeepCopy() *DescribeRegistryResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeRegistryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeRepositoriesRequest) DeepCopyInto(out *DescribeRepositoriesRequest) {
	*out = *in
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryNames != nil {
		in, out := &in.RepositoryNames, &out.RepositoryNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeRepositoriesRequest.
func (in *DescribeRepositoriesRequest) DeepCopy() *DescribeRepositoriesRequest {
	if in == nil {
		return nil
	}
	out := new(DescribeRepositoriesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescribeRepositoriesResponse) DeepCopyInto(out *DescribeRepositoriesResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]*Repository_SDK, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Repository_SDK)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescribeRepositoriesResponse.
func (in *DescribeRepositoriesResponse) DeepCopy() *DescribeRepositoriesResponse {
	if in == nil {
		return nil
	}
	out := new(DescribeRepositoriesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionConfiguration) DeepCopyInto(out *EncryptionConfiguration) {
	*out = *in
	if in.EncryptionType != nil {
		in, out := &in.EncryptionType, &out.EncryptionType
		*out = new(string)
		**out = **in
	}
	if in.KMSKey != nil {
		in, out := &in.KMSKey, &out.KMSKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionConfiguration.
func (in *EncryptionConfiguration) DeepCopy() *EncryptionConfiguration {
	if in == nil {
		return nil
	}
	out := new(EncryptionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnhancedImageScanFinding) DeepCopyInto(out *EnhancedImageScanFinding) {
	*out = *in
	if in.AWSAccountID != nil {
		in, out := &in.AWSAccountID, &out.AWSAccountID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnhancedImageScanFinding.
func (in *EnhancedImageScanFinding) DeepCopy() *EnhancedImageScanFinding {
	if in == nil {
		return nil
	}
	out := new(EnhancedImageScanFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetDownloadURLForLayerRequest) DeepCopyInto(out *GetDownloadURLForLayerRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetDownloadURLForLayerRequest.
func (in *GetDownloadURLForLayerRequest) DeepCopy() *GetDownloadURLForLayerRequest {
	if in == nil {
		return nil
	}
	out := new(GetDownloadURLForLayerRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetDownloadURLForLayerResponse) DeepCopyInto(out *GetDownloadURLForLayerResponse) {
	*out = *in
	if in.DownloadURL != nil {
		in, out := &in.DownloadURL, &out.DownloadURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetDownloadURLForLayerResponse.
func (in *GetDownloadURLForLayerResponse) DeepCopy() *GetDownloadURLForLayerResponse {
	if in == nil {
		return nil
	}
	out := new(GetDownloadURLForLayerResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetLifecyclePolicyPreviewRequest) DeepCopyInto(out *GetLifecyclePolicyPreviewRequest) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetLifecyclePolicyPreviewRequest.
func (in *GetLifecyclePolicyPreviewRequest) DeepCopy() *GetLifecyclePolicyPreviewRequest {
	if in == nil {
		return nil
	}
	out := new(GetLifecyclePolicyPreviewRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetLifecyclePolicyPreviewResponse) DeepCopyInto(out *GetLifecyclePolicyPreviewResponse) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetLifecyclePolicyPreviewResponse.
func (in *GetLifecyclePolicyPreviewResponse) DeepCopy() *GetLifecyclePolicyPreviewResponse {
	if in == nil {
		return nil
	}
	out := new(GetLifecyclePolicyPreviewResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetLifecyclePolicyRequest) DeepCopyInto(out *GetLifecyclePolicyRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetLifecyclePolicyRequest.
func (in *GetLifecyclePolicyRequest) DeepCopy() *GetLifecyclePolicyRequest {
	if in == nil {
		return nil
	}
	out := new(GetLifecyclePolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetLifecyclePolicyResponse) DeepCopyInto(out *GetLifecyclePolicyResponse) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetLifecyclePolicyResponse.
func (in *GetLifecyclePolicyResponse) DeepCopy() *GetLifecyclePolicyResponse {
	if in == nil {
		return nil
	}
	out := new(GetLifecyclePolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetRegistryPolicyResponse) DeepCopyInto(out *GetRegistryPolicyResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRegistryPolicyResponse.
func (in *GetRegistryPolicyResponse) DeepCopy() *GetRegistryPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(GetRegistryPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetRegistryScanningConfigurationResponse) DeepCopyInto(out *GetRegistryScanningConfigurationResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRegistryScanningConfigurationResponse.
func (in *GetRegistryScanningConfigurationResponse) DeepCopy() *GetRegistryScanningConfigurationResponse {
	if in == nil {
		return nil
	}
	out := new(GetRegistryScanningConfigurationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetRepositoryPolicyRequest) DeepCopyInto(out *GetRepositoryPolicyRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRepositoryPolicyRequest.
func (in *GetRepositoryPolicyRequest) DeepCopy() *GetRepositoryPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(GetRepositoryPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetRepositoryPolicyResponse) DeepCopyInto(out *GetRepositoryPolicyResponse) {
	*out = *in
	if in.PolicyText != nil {
		in, out := &in.PolicyText, &out.PolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRepositoryPolicyResponse.
func (in *GetRepositoryPolicyResponse) DeepCopy() *GetRepositoryPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(GetRepositoryPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageDetail) DeepCopyInto(out *ImageDetail) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageDetail.
func (in *ImageDetail) DeepCopy() *ImageDetail {
	if in == nil {
		return nil
	}
	out := new(ImageDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageReplicationStatus) DeepCopyInto(out *ImageReplicationStatus) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReplicationStatus.
func (in *ImageReplicationStatus) DeepCopy() *ImageReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ImageReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanFinding) DeepCopyInto(out *ImageScanFinding) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanFinding.
func (in *ImageScanFinding) DeepCopy() *ImageScanFinding {
	if in == nil {
		return nil
	}
	out := new(ImageScanFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageScanningConfiguration) DeepCopyInto(out *ImageScanningConfiguration) {
	*out = *in
	if in.ScanOnPush != nil {
		in, out := &in.ScanOnPush, &out.ScanOnPush
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageScanningConfiguration.
func (in *ImageScanningConfiguration) DeepCopy() *ImageScanningConfiguration {
	if in == nil {
		return nil
	}
	out := new(ImageScanningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiateLayerUploadRequest) DeepCopyInto(out *InitiateLayerUploadRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiateLayerUploadRequest.
func (in *InitiateLayerUploadRequest) DeepCopy() *InitiateLayerUploadRequest {
	if in == nil {
		return nil
	}
	out := new(InitiateLayerUploadRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvalidLayerPartException) DeepCopyInto(out *InvalidLayerPartException) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvalidLayerPartException.
func (in *InvalidLayerPartException) DeepCopy() *InvalidLayerPartException {
	if in == nil {
		return nil
	}
	out := new(InvalidLayerPartException)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListImagesRequest) DeepCopyInto(out *ListImagesRequest) {
	*out = *in
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int64)
		**out = **in
	}
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListImagesRequest.
func (in *ListImagesRequest) DeepCopy() *ListImagesRequest {
	if in == nil {
		return nil
	}
	out := new(ListImagesRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListImagesResponse) DeepCopyInto(out *ListImagesResponse) {
	*out = *in
	if in.NextToken != nil {
		in, out := &in.NextToken, &out.NextToken
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListImagesResponse.
func (in *ListImagesResponse) DeepCopy() *ListImagesResponse {
	if in == nil {
		return nil
	}
	out := new(ListImagesResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTagsForResourceRequest) DeepCopyInto(out *ListTagsForResourceRequest) {
	*out = *in
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTagsForResourceRequest.
func (in *ListTagsForResourceRequest) DeepCopy() *ListTagsForResourceRequest {
	if in == nil {
		return nil
	}
	out := new(ListTagsForResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListTagsForResourceResponse) DeepCopyInto(out *ListTagsForResourceResponse) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListTagsForResourceResponse.
func (in *ListTagsForResourceResponse) DeepCopy() *ListTagsForResourceResponse {
	if in == nil {
		return nil
	}
	out := new(ListTagsForResourceResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageVulnerabilityDetails) DeepCopyInto(out *PackageVulnerabilityDetails) {
	*out = *in
	if in.SourceURL != nil {
		in, out := &in.SourceURL, &out.SourceURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageVulnerabilityDetails.
func (in *PackageVulnerabilityDetails) DeepCopy() *PackageVulnerabilityDetails {
	if in == nil {
		return nil
	}
	out := new(PackageVulnerabilityDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullThroughCacheRule) DeepCopyInto(out *PullThroughCacheRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullThroughCacheRule.
func (in *PullThroughCacheRule) DeepCopy() *PullThroughCacheRule {
	if in == nil {
		return nil
	}
	out := new(PullThroughCacheRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullThroughCacheRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullThroughCacheRuleList) DeepCopyInto(out *PullThroughCacheRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PullThroughCacheRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullThroughCacheRuleList.
func (in *PullThroughCacheRuleList) DeepCopy() *PullThroughCacheRuleList {
	if in == nil {
		return nil
	}
	out := new(PullThroughCacheRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullThroughCacheRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullThroughCacheRuleSpec) DeepCopyInto(out *PullThroughCacheRuleSpec) {
	*out = *in
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistry != nil {
		in, out := &in.UpstreamRegistry, &out.UpstreamRegistry
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistryURL != nil {
		in, out := &in.UpstreamRegistryURL, &out.UpstreamRegistryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullThroughCacheRuleSpec.
func (in *PullThroughCacheRuleSpec) DeepCopy() *PullThroughCacheRuleSpec {
	if in == nil {
		return nil
	}
	out := new(PullThroughCacheRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullThroughCacheRuleStatus) DeepCopyInto(out *PullThroughCacheRuleStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullThroughCacheRuleStatus.
func (in *PullThroughCacheRuleStatus) DeepCopy() *PullThroughCacheRuleStatus {
	if in == nil {
		return nil
	}
	out := new(PullThroughCacheRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullThroughCacheRule_SDK) DeepCopyInto(out *PullThroughCacheRule_SDK) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.UpstreamRegistry != nil {
		in, out := &in.UpstreamRegistry, &out.UpstreamRegistry
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistryURL != nil {
		in, out := &in.UpstreamRegistryURL, &out.UpstreamRegistryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullThroughCacheRule_SDK.
func (in *PullThroughCacheRule_SDK) DeepCopy() *PullThroughCacheRule_SDK {
	if in == nil {
		return nil
	}
	out := new(PullThroughCacheRule_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutImageRequest) DeepCopyInto(out *PutImageRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutImageRequest.
func (in *PutImageRequest) DeepCopy() *PutImageRequest {
	if in == nil {
		return nil
	}
	out := new(PutImageRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutImageScanningConfigurationRequest) DeepCopyInto(out *PutImageScanningConfigurationRequest) {
	*out = *in
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutImageScanningConfigurationRequest.
func (in *PutImageScanningConfigurationRequest) DeepCopy() *PutImageScanningConfigurationRequest {
	if in == nil {
		return nil
	}
	out := new(PutImageScanningConfigurationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutImageScanningConfigurationResponse) DeepCopyInto(out *PutImageScanningConfigurationResponse) {
	*out = *in
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutImageScanningConfigurationResponse.
func (in *PutImageScanningConfigurationResponse) DeepCopy() *PutImageScanningConfigurationResponse {
	if in == nil {
		return nil
	}
	out := new(PutImageScanningConfigurationResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutImageTagMutabilityRequest) DeepCopyInto(out *PutImageTagMutabilityRequest) {
	*out = *in
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutImageTagMutabilityRequest.
func (in *PutImageTagMutabilityRequest) DeepCopy() *PutImageTagMutabilityRequest {
	if in == nil {
		return nil
	}
	out := new(PutImageTagMutabilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutImageTagMutabilityResponse) DeepCopyInto(out *PutImageTagMutabilityResponse) {
	*out = *in
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutImageTagMutabilityResponse.
func (in *PutImageTagMutabilityResponse) DeepCopy() *PutImageTagMutabilityResponse {
	if in == nil {
		return nil
	}
	out := new(PutImageTagMutabilityResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutLifecyclePolicyRequest) DeepCopyInto(out *PutLifecyclePolicyRequest) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutLifecyclePolicyRequest.
func (in *PutLifecyclePolicyRequest) DeepCopy() *PutLifecyclePolicyRequest {
	if in == nil {
		return nil
	}
	out := new(PutLifecyclePolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutLifecyclePolicyResponse) DeepCopyInto(out *PutLifecyclePolicyResponse) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutLifecyclePolicyResponse.
func (in *PutLifecyclePolicyResponse) DeepCopy() *PutLifecyclePolicyResponse {
	if in == nil {
		return nil
	}
	out := new(PutLifecyclePolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PutRegistryPolicyResponse) DeepCopyInto(out *PutRegistryPolicyResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PutRegistryPolicyResponse.
func (in *PutRegistryPolicyResponse) DeepCopy() *PutRegistryPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(PutRegistryPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendation) DeepCopyInto(out *Recommendation) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendation.
func (in *Recommendation) DeepCopy() *Recommendation {
	if in == nil {
		return nil
	}
	out := new(Recommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationDestination) DeepCopyInto(out *ReplicationDestination) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationDestination.
func (in *ReplicationDestination) DeepCopy() *ReplicationDestination {
	if in == nil {
		return nil
	}
	out := new(ReplicationDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryScanningConfiguration) DeepCopyInto(out *RepositoryScanningConfiguration) {
	*out = *in
	if in.RepositoryARN != nil {
		in, out := &in.RepositoryARN, &out.RepositoryARN
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
	if in.ScanOnPush != nil {
		in, out := &in.ScanOnPush, &out.ScanOnPush
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryScanningConfiguration.
func (in *RepositoryScanningConfiguration) DeepCopy() *RepositoryScanningConfiguration {
	if in == nil {
		return nil
	}
	out := new(RepositoryScanningConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryScanningConfigurationFailure) DeepCopyInto(out *RepositoryScanningConfigurationFailure) {
	*out = *in
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryScanningConfigurationFailure.
func (in *RepositoryScanningConfigurationFailure) DeepCopy() *RepositoryScanningConfigurationFailure {
	if in == nil {
		return nil
	}
	out := new(RepositoryScanningConfigurationFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	if in.EncryptionConfiguration != nil {
		in, out := &in.EncryptionConfiguration, &out.EncryptionConfiguration
		*out = new(EncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.LifecyclePolicy != nil {
		in, out := &in.LifecyclePolicy, &out.LifecyclePolicy
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(Repository_SDK)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository_SDK) DeepCopyInto(out *Repository_SDK) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.EncryptionConfiguration != nil {
		in, out := &in.EncryptionConfiguration, &out.EncryptionConfiguration
		*out = new(EncryptionConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageScanningConfiguration != nil {
		in, out := &in.ImageScanningConfiguration, &out.ImageScanningConfiguration
		*out = new(ImageScanningConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageTagMutability != nil {
		in, out := &in.ImageTagMutability, &out.ImageTagMutability
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryARN != nil {
		in, out := &in.RepositoryARN, &out.RepositoryARN
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
	if in.RepositoryURI != nil {
		in, out := &in.RepositoryURI, &out.RepositoryURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository_SDK.
func (in *Repository_SDK) DeepCopy() *Repository_SDK {
	if in == nil {
		return nil
	}
	out := new(Repository_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetRepositoryPolicyRequest) DeepCopyInto(out *SetRepositoryPolicyRequest) {
	*out = *in
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
	if in.PolicyText != nil {
		in, out := &in.PolicyText, &out.PolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetRepositoryPolicyRequest.
func (in *SetRepositoryPolicyRequest) DeepCopy() *SetRepositoryPolicyRequest {
	if in == nil {
		return nil
	}
	out := new(SetRepositoryPolicyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetRepositoryPolicyResponse) DeepCopyInto(out *SetRepositoryPolicyResponse) {
	*out = *in
	if in.PolicyText != nil {
		in, out := &in.PolicyText, &out.PolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetRepositoryPolicyResponse.
func (in *SetRepositoryPolicyResponse) DeepCopy() *SetRepositoryPolicyResponse {
	if in == nil {
		return nil
	}
	out := new(SetRepositoryPolicyResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartImageScanRequest) DeepCopyInto(out *StartImageScanRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartImageScanRequest.
func (in *StartImageScanRequest) DeepCopy() *StartImageScanRequest {
	if in == nil {
		return nil
	}
	out := new(StartImageScanRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartImageScanResponse) DeepCopyInto(out *StartImageScanResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartImageScanResponse.
func (in *StartImageScanResponse) DeepCopy() *StartImageScanResponse {
	if in == nil {
		return nil
	}
	out := new(StartImageScanResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartLifecyclePolicyPreviewRequest) DeepCopyInto(out *StartLifecyclePolicyPreviewRequest) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartLifecyclePolicyPreviewRequest.
func (in *StartLifecyclePolicyPreviewRequest) DeepCopy() *StartLifecyclePolicyPreviewRequest {
	if in == nil {
		return nil
	}
	out := new(StartLifecyclePolicyPreviewRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartLifecyclePolicyPreviewResponse) DeepCopyInto(out *StartLifecyclePolicyPreviewResponse) {
	*out = *in
	if in.LifecyclePolicyText != nil {
		in, out := &in.LifecyclePolicyText, &out.LifecyclePolicyText
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartLifecyclePolicyPreviewResponse.
func (in *StartLifecyclePolicyPreviewResponse) DeepCopy() *StartLifecyclePolicyPreviewResponse {
	if in == nil {
		return nil
	}
	out := new(StartLifecyclePolicyPreviewResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagResourceRequest) DeepCopyInto(out *TagResourceRequest) {
	*out = *in
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagResourceRequest.
func (in *TagResourceRequest) DeepCopy() *TagResourceRequest {
	if in == nil {
		return nil
	}
	out := new(TagResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UntagResourceRequest) DeepCopyInto(out *UntagResourceRequest) {
	*out = *in
	if in.ResourceARN != nil {
		in, out := &in.ResourceARN, &out.ResourceARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UntagResourceRequest.
func (in *UntagResourceRequest) DeepCopy() *UntagResourceRequest {
	if in == nil {
		return nil
	}
	out := new(UntagResourceRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePullThroughCacheRuleRequest) DeepCopyInto(out *UpdatePullThroughCacheRuleRequest) {
	*out = *in
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePullThroughCacheRuleRequest.
func (in *UpdatePullThroughCacheRuleRequest) DeepCopy() *UpdatePullThroughCacheRuleRequest {
	if in == nil {
		return nil
	}
	out := new(UpdatePullThroughCacheRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdatePullThroughCacheRuleResponse) DeepCopyInto(out *UpdatePullThroughCacheRuleResponse) {
	*out = *in
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdatePullThroughCacheRuleResponse.
func (in *UpdatePullThroughCacheRuleResponse) DeepCopy() *UpdatePullThroughCacheRuleResponse {
	if in == nil {
		return nil
	}
	out := new(UpdatePullThroughCacheRuleResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadLayerPartRequest) DeepCopyInto(out *UploadLayerPartRequest) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadLayerPartRequest.
func (in *UploadLayerPartRequest) DeepCopy() *UploadLayerPartRequest {
	if in == nil {
		return nil
	}
	out := new(UploadLayerPartRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UploadLayerPartResponse) DeepCopyInto(out *UploadLayerPartResponse) {
	*out = *in
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UploadLayerPartResponse.
func (in *UploadLayerPartResponse) DeepCopy() *UploadLayerPartResponse {
	if in == nil {
		return nil
	}
	out := new(UploadLayerPartResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatePullThroughCacheRuleRequest) DeepCopyInto(out *ValidatePullThroughCacheRuleRequest) {
	*out = *in
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatePullThroughCacheRuleRequest.
func (in *ValidatePullThroughCacheRuleRequest) DeepCopy() *ValidatePullThroughCacheRuleRequest {
	if in == nil {
		return nil
	}
	out := new(ValidatePullThroughCacheRuleRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatePullThroughCacheRuleResponse) DeepCopyInto(out *ValidatePullThroughCacheRuleResponse) {
	*out = *in
	if in.CredentialARN != nil {
		in, out := &in.CredentialARN, &out.CredentialARN
		*out = new(string)
		**out = **in
	}
	if in.ECRRepositoryPrefix != nil {
		in, out := &in.ECRRepositoryPrefix, &out.ECRRepositoryPrefix
		*out = new(string)
		**out = **in
	}
	if in.RegistryID != nil {
		in, out := &in.RegistryID, &out.RegistryID
		*out = new(string)
		**out = **in
	}
	if in.UpstreamRegistryURL != nil {
		in, out := &in.UpstreamRegistryURL, &out.UpstreamRegistryURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatePullThroughCacheRuleResponse.
func (in *ValidatePullThroughCacheRuleResponse) DeepCopy() *ValidatePullThroughCacheRuleResponse {
	if in == nil {
		return nil
	}
	out := new(ValidatePullThroughCacheRuleResponse)
	in.DeepCopyInto(out)
	return out
}
